shallow_clone: true

os:
  - Visual Studio 2015

environment:
  matrix:
  - TOOLSET: vs2015

install:
  - ps: Start-FileDownload 'https://github.com/premake/premake-core/releases/download/v5.0.0-alpha11/premake-5.0.0-alpha11-windows.zip' 'premake.zip'
  - 7z x premake.zip
  - premake5.exe %TOOLSET%
  - cmd: >-
      cd c:\    
      IF NOT EXIST c:\vcpkg\ ( git clone https://github.com/Microsoft/vcpkg ) ELSE ( echo VCPKG is cached )
      cd vcpkg
      powershell -exec bypass scripts\bootstrap.ps1
      .\vcpkg integrate install
      .\vcpkg install png

configuration:
  - Release

build:
  project: guetzli.sln

cache: c:\vcpkg\ -> appveyor.yml
